language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

install:
    - pip install --upgrade pip setuptools wheel
    - python setup.py install

# Tests are inside modules (doctest)
script:
    - ./coverage_and_test.sh

after_success:
    coveralls
