language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

install:
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt
    - python setup.py install

# Tests are inside modules (doctest)
script:
    - ./coverage_and_test.sh
    - git-r pull i_am_a_repo

after_success:
    coveralls
