#!/usr/bin/python
## Author: j.peloton@sussex.ac.uk
from __future__ import division, absolute_import, print_function

import sys
from gitrconfig import Repository

if __name__ == "__main__":
    """
    """
    ## Grab args
    command = sys.argv[1]
    reponame = sys.argv[2]
    option = sys.argv[3:]

    ## Handle no option case
    if option == []:
        option = ''

    ## Run the command
    r = Repository(reponame)
    r.run(command, option)
